[package]
name = "diffy"
version = "0.0.0"
authors = ["Brandon Williams <bwilliams.eng@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Tools for finding and manipulating differences between files"
edition = "2018"

[dependencies]
